name: "构建MarkVision应用"

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 设置Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: 安装Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: 安装依赖
        run: npm install
        
      - name: 构建前端
        run: npm run build
        
      - name: 构建并发布Tauri应用
        uses: tauri-apps/tauri-action@v0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "MarkVision v__VERSION__"
          releaseBody: "MarkVision便携版发布，包含可执行文件和安装包"
          releaseDraft: false
          prerelease: false
          includeUpdaterJson: true
          includeRelease: true
          args: --target x86_64-pc-windows-msvc
          
      # 确保找到并发布便携版exe文件
      - name: 查找构建产物
        id: find-artifacts
        run: |
          echo "::set-output name=portable_exe::$(Get-ChildItem -Path './src-tauri/target/x86_64-pc-windows-msvc/release/MarkVision.exe' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName)"
          echo "::set-output name=setup_exe::$(Get-ChildItem -Path './src-tauri/target/x86_64-pc-windows-msvc/release/bundle/nsis/*.exe' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName)"
          echo "::set-output name=msi_installer::$(Get-ChildItem -Path './src-tauri/target/x86_64-pc-windows-msvc/release/bundle/msi/*.msi' -ErrorAction SilentlyContinue | Select-Object -ExpandProperty FullName)"
        shell: pwsh
        
      - name: 手动上传便携版到Release
        if: steps.find-artifacts.outputs.portable_exe != ''
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.find-artifacts.outputs.portable_exe }}
          tag_name: v__VERSION__
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}