name: "构建MarkVision应用"

on:
  push:
    branches: [ main, master ]  # 支持main或master分支
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      
      - name: 设置Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          cache: 'npm'
          
      - name: 安装Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          
      - name: 安装依赖
        run: npm install
        
      - name: 构建前端
        run: npm run build
        
      - name: 构建Tauri应用
        uses: tauri-apps/tauri-action@v0.2
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: "MarkVision v__VERSION__"
          releaseBody: "MarkVision Windows版本发布"
          releaseDraft: true
          prerelease: false
          
      - name: 上传构建产物
        uses: actions/upload-artifact@v2.3.1
        with:
          name: MarkVision-windows
          path: src-tauri/target/release/bundle/