   name: "构建MarkVision应用"
   
   on:
     push:
       branches: [ main, master ]  # 支持main或master分支
     workflow_dispatch:  # 允许手动触发
   
   jobs:
     build-windows:
       runs-on: windows-latest
       steps:
         - uses: actions/checkout@v3
         
         - name: 设置Node.js
           uses: actions/setup-node@v3
           with:
             node-version: 16
             cache: 'npm'
             
         - name: 安装Rust
           uses: dtolnay/rust-toolchain@stable
           
         - name: 安装依赖
           run: npm install
           
         - name: 构建前端
           run: npm run build
           
         - name: 构建Tauri应用
           uses: tauri-apps/tauri-action@v0
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           with:
             tagName: v__VERSION__
             releaseName: "MarkVision v__VERSION__"
             releaseBody: "MarkVision Windows版本发布"
             releaseDraft: true
             prerelease: false
             
         - name: 上传构建产物
           uses: actions/upload-artifact@v3
           with:
             name: MarkVision-windows
             path: src-tauri/target/release/bundle/