name: "构建MarkVision应用"

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

# 添加权限配置
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 设置Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: 安装Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          
      - name: 安装依赖
        run: npm install
        
      - name: 构建前端
        run: npm run build
        
      - name: 构建并发布Tauri应用
        uses: tauri-apps/tauri-action@v0.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: "MarkVision v__VERSION__"
          releaseBody: "MarkVision Windows版本发布"
          releaseDraft: true
          prerelease: false